version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "node-songs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bj1yglddqpax"
s3_prefix = "node-songs"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
